name: Generate Datas

on:
  schedule: # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # Permite rodar manualmente também

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Gera a cobrinha SVG
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: LiviaRosaa
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publica o SVG no branch "output"
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
